server:
  port: 8005
spring:
  application:
    name: service-moneystore
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000